In [2]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
import matplotlib.pylab as plt
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [3]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [10]:
net = simpleNet()
print(net.W)

x = np.array([.6, .9])
p = net.predict(x)
print(p)
print(np.argmax(p))

t = np.array([0, 0, 1])
print(net.loss(x, t))

[[-1.24329938 -0.36239383 -0.58587951]
 [ 1.05573051 -0.31657686 -0.42370832]]
[ 0.20417783 -0.50235547 -0.73286519]
0
1.5710430772229738


In [11]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.3182794   0.15702363 -0.47530303]
 [ 0.4774191   0.23553545 -0.71295454]]
